version: "3"

services:
  discord-bot:
    build: .
    image: you-owe-me-money
    environment:
      - DISCORD_BOT_TOKEN=${TOKEN}
    volumes:
      - .:/opt/apps/discord-bot
    container_name: discord-bot
